### ISSUE TITLE
weights argument 

### ISSUE THREAD

**Issue by oezgesahin** [tnagler/vinereg#13]
Hi, 

when I provide weights for observations, it raises a size error: "Error: sizes of weights and data don't match."  Could you check it? 

set.seed(2)
x <- matrix(rnorm(200), 100, 2)
y <- x %*% c(1, -2)
dat <- data.frame(y = y, x = x, z = as.factor(rbinom(100, 2, 0.5)))
ww <- rep(1, nrow(data))
fit <- vinereg(formula=y ~ ., data=dat, weights = ww)

**Comment by tnagler** [comment]
fixed in #14, thanks!
