### ISSUE TITLE
cpdf assign wrong values to hfunc2_sub

### ISSUE THREAD

**Issue by FLBuchner** [tnagler/vinereg#16]
Hi Thomas,

this is somewhat related to vinecopulib/vinecopulib#591.

https://github.com/tnagler/vinereg/blob/beed02ab9096f7017d857479733a33a9ba49ddbc/src/vinereg.cpp#L345

Does not work as intended imo. In the example below disc_cols is [0,0,0,0] but should be [0,0,0,1].
In both cases, hfunc2_sub has the wrong values from

https://github.com/tnagler/vinereg/blob/beed02ab9096f7017d857479733a33a9ba49ddbc/src/vinereg.cpp#L362C1-L368C10

I think this should be the same as in cpit

https://github.com/tnagler/vinereg/blob/beed02ab9096f7017d857479733a33a9ba49ddbc/src/vinereg.cpp#L259C9-L265C10

Here is an example. In cpit and cpdf I printed the values of disc_cols and hfunc2_sub to console in my own vinereg version:

library(vinereg)
set.seed(318)

x <- matrix(rnorm(200), 100, 2)
y <- x %*% c(1, -2)
dat <- data.frame(y = y, x = x, z = as.factor(rbinom(100, 2, 0.5)))

(fit <- vinereg(y ~ x.1 + x.2 + z, dat))
cpit(fit, dat[1,])
cpdf(fit, dat[1,])

Best,
Ferdinand

**Comment by tnagler** [comment]
This indeed looks fishy. My initial impression is that the one in `cond_dens_cpp` is wrong, because `get_disc_cols()` only makes sense in connection with `collapse_data`:
https://github.com/vinecopulib/vinecopulib/blob/258eb2d7758ce067ee7d53789067f0d3ebbb9375/include/vinecopulib/vinecop/implementation/class.ipp#L1416-L1430

Can't look much deeper into this now. Do you maybe have a way to check which one is correct?

**Comment by FLBuchner** [comment]
I also think `cond_dens_cpp` is wrong. As a test I compared the objects in `cpit` and `cpdf` for the same data point. 

`hfunc2_sub[3]` is where something needs to be assigned.

`cpit` has for `hfunc2_sub[3]` = 1e-10 
`cpdf` has here `hfunc2_sub[3]` = 0.0490473 but this is the data entry of the first variable `u[0]` and `u[d+0]`, which does not make sense.

`cpit`
> cpit(fit, dat[1,])
var_types_: c, c, c, d, 
d: 4
order: 1, 3, 2, 4, 
Input data: 
u[0], u[1], u[2], [3]: 
0.0490473, 0.146203, 0.931451, 0.465736, 
u[d+0], u[d+1], u[d+2], [d+3]: 
0.0490473, 0.146203, 0.931451, 1e-10, 
hfunc2 values in natural order: 
hfunc2: 0.0490473  0.931451  0.146203  0.465736
hfunc2_sub:     0     0     0 1e-10
[1] 0.7476287

`cpdf`
> cpdf(fit, dat[1,])
var_types_: c, c, c, d, 
d: 4
order: 1, 3, 2, 4, 
Input data: 
u[0], u[1], u[2], [3]: 
0.0490473, 0.146203, 0.931451, 0.465736, 
u[d+0], u[d+1], u[d+2], [d+3]: 
0.0490473, 0.146203, 0.931451, 1e-10, 
hfunc2 values in natural order: 
hfunc2: 0.0490473  0.931451  0.146203  0.465736
hfunc2_sub:         0         0         0 0.0490473
[1] 2.387678
