### ISSUE TITLE
Getting an error 'Error in -2 * var_cll : non-numeric argument to binary operator'

### ISSUE THREAD

**Issue by ArjunReddy07** [tnagler/vinereg#9]
Hi,

 I am running 'vinereg' for different sets of data. I have one response variable and three independent variables ( I do not explicitly know the relation between them).

* The code used looks like the below, each variable is a column of size 911.
   av <-data.frame(y=input_data_raw, x1=input_data_raw_1, x2=input_data_raw_2, x3=input_data_raw_3)
  vine_reg_model_raw_data <- vinereg(y ~ ., av)

* The nature of the data is such that y takes the column of numbers between (-1,1) and the independent variables take the values between (0, 1).

* For some sets of the initialized y, x1, x2, and x3 (each of them are columns of size 911), there is no error in the QR, but for some sets of initialized data, I am getting the following error '**Error in -2 * var_cll : non-numeric argument to binary operator**'

* A traceback is showing the following
    '**2: finalize_vinereg_object(formula = formula, selcrit = selcrit, 
       model_frame = mf, margins = margins, vine = fit$vine, selected_vars = fit$selected_vars, 
       var_nms = colnames(mfx))
1: vinereg(y ~ ., av)**'

I am not able to understand the cause for such an error, would be helpful if resolved. Thank you.

**Comment by tnagler** [comment]
Is it possible to give a reproducible example? (You can also send me an email if you don't want to post data publicly.) I have an idea what is happening, but without example, it's very hard to find out why.

**Comment by ArjunReddy07** [comment]
Ok sure, thank you.

**Comment by ArjunReddy07** [comment]
Please use the attached code snippet and the data from the excel file. This
is one instance where there is an error. For some other similar instances
of data, 'vinereg' is working fine. Please let me know if any concerns.

Sincerely,
Arjun

**Comment by tnagler** [comment]
There's no attachment, please send to [mail@tnagler.com](mailto:mail@tnagler.com).

**Comment by tnagler** [comment]
Alright, so in your example, no covariates were selected to have predictive power. This case wasn't handled properly in the library, should be fixed now. You can install an updated version with
``` r
devtools::install_github("tnagler/vinereg")
```
I'll submit the new version to CRAN soon.

**Comment by tnagler** [comment]
Alright, so in your example, no covariates were selected to have predictive power. This case wasn't handled properly in the library, should be fixed now. You can install an updated version with
``` r
devtools::install_github("tnagler/vinereg")
```
I'll submit the new version to CRAN soon.

**Comment by ArjunReddy07** [comment]
ok, I was not able to think about this case. Thank you for the help. I will
install the updated version and try again.
